package database

import (
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"log"
	"os"
	"time"

	"freedom-cry/internal/config"
	"freedom-cry/internal/models"
	"freedom-cry/internal/protocol/amneziawg"
	"freedom-cry/internal/protocol/xray"

	"golang.org/x/crypto/bcrypt"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
)

func Connect(cfg *config.DatabaseConfig) (*gorm.DB, error) {
	dsn := fmt.Sprintf(
		"host=%s user=%s password=%s dbname=%s port=%d sslmode=%s TimeZone=UTC",
		cfg.Host, cfg.User, cfg.Password, cfg.DBName, cfg.Port, cfg.SSLMode,
	)

	db, err := gorm.Open(postgres.Open(dsn), &gorm.Config{
		Logger: logger.Default.LogMode(logger.Warn),
	})
	if err != nil {
		return nil, fmt.Errorf("failed to connect to database: %w", err)
	}

	sqlDB, err := db.DB()
	if err != nil {
		return nil, err
	}

	sqlDB.SetMaxIdleConns(10)
	sqlDB.SetMaxOpenConns(100)
	sqlDB.SetConnMaxLifetime(time.Hour)

	// Run migrations
	if err := db.AutoMigrate(
		&models.User{},
		&models.Plan{},
		&models.ServerNode{},
		&models.Subscription{},
		&models.ClientKey{},
		&models.Transaction{},
		&models.RedeemedBlindToken{},
	); err != nil {
		return nil, fmt.Errorf("failed to run migrations: %w", err)
	}

	// Security Hardening Migration: Explicitly drop any legacy plaintext private key columns
	// from database tables so that secrets are erased at the schema level.
	_ = db.Exec("ALTER TABLE server_nodes DROP COLUMN IF EXISTS reality_priv_key, DROP COLUMN IF EXISTS awg_priv_key").Error
	_ = db.Exec("ALTER TABLE client_keys DROP COLUMN IF EXISTS awg_private_key").Error
	// Subnet Routing Hardening: Update any legacy /24 subnets to /16 dual-stack
	_ = db.Model(&models.ServerNode{}).Where("awg_server_subnet = ? OR awg_server_subnet = ?", "10.8.0.0/24", "10.8.0.1/24").Update("awg_server_subnet", "10.8.0.1/16, fd00:8::1/64").Error

	log.Println("[Database] Schema migrations, key cleanup, and subnet hardening applied successfully")

	// Seed default data if empty
	SeedDefaults(db)

	return db, nil
}

func SeedDefaults(db *gorm.DB) {
	// 1. Seed Admin user if no admin exists
	var adminCount int64
	db.Model(&models.User{}).Where("role = ?", models.RoleAdmin).Count(&adminCount)
	if adminCount == 0 {
		adminPass := os.Getenv("ADMIN_INITIAL_PASSWORD")
		isAutoGenerated := false
		if adminPass == "" {
			// Generate cryptographically secure random 24-character password
			rnd := make([]byte, 16)
			_, _ = rand.Read(rnd)
			adminPass = hex.EncodeToString(rnd)
			isAutoGenerated = true
		}

		hashed, err := bcrypt.GenerateFromPassword([]byte(adminPass), 12)
		if err == nil {
			admin := models.User{
				Email:        "admin@freedomcry.net",
				PasswordHash: string(hashed),
				Role:         models.RoleAdmin,
				Balance:      1000.00,
				IsActive:     true,
			}
			if err := db.Create(&admin).Error; err == nil {
				if isAutoGenerated {
					log.Printf("[Security] Initial Admin created with randomly generated password: %s", adminPass)
					log.Printf("[Security] Save this password immediately. Set ADMIN_INITIAL_PASSWORD to define custom.")
				} else {
					log.Println("[Security] Initial Admin created with configured password")
				}
			}
		}
	}

	// 2. Seed Default Plans
	var planCount int64
	db.Model(&models.Plan{}).Count(&planCount)
	if planCount == 0 {
		plans := []models.Plan{
			{
				Name:             "Freedom Starter (1 Month)",
				Description:      "Uncapped speed, VLESS-Reality & AmneziaWG, 100 GB traffic",
				Price:            199.00,
				DurationDays:     30,
				TrafficLimitGB:   100,
				AllowedProtocols: "vless,awg",
				IsActive:         true,
			},
			{
				Name:             "Freedom Unlimited (3 Months)",
				Description:      "Unlimited traffic, All locations, Priority nodes",
				Price:            499.00,
				DurationDays:     90,
				TrafficLimitGB:   0, // Unlimited
				AllowedProtocols: "vless,awg",
				IsActive:         true,
			},
			{
				Name:             "Freedom Year Pass (12 Months)",
				Description:      "Maximum savings, All protocols + Early access to new bypasses",
				Price:            1490.00,
				DurationDays:     365,
				TrafficLimitGB:   0,
				AllowedProtocols: "vless,awg",
				IsActive:         true,
			},
		}
		for _, p := range plans {
			db.Create(&p)
		}
		log.Println("[Seed] Default plans created")
	}

	// 3. Seed Demo Node if no nodes exist (without private keys!)
	var nodeCount int64
	db.Model(&models.ServerNode{}).Count(&nodeCount)
	if nodeCount == 0 {
		xrayKeys, _ := xray.GenerateRealityKeyPair()
		awgKeys, _ := amneziawg.GenerateAWGKeyPair()
		awgParams, _ := amneziawg.GenerateDefaultObfuscationParams()

		if xrayKeys != nil && awgKeys != nil && awgParams != nil {
			// Generate one-time initial node secret token
			tokenRaw := make([]byte, 32)
			_, _ = rand.Read(tokenRaw)
			tokenHex := hex.EncodeToString(tokenRaw)
			tokenHash := sha256.Sum256([]byte(tokenHex))

			demoNode := models.ServerNode{
				Name:              "Amsterdam #1 (Fast)",
				Country:           "Netherlands",
				CountryCode:       "NL",
				Host:              "nl1.freedomcry.net",
				IsOnline:          true,
				LoadPercent:       12,
				AuthTokenHash:     hex.EncodeToString(tokenHash[:]),
				LastAllocatedIP:   1,
				VlessEnabled:      true,
				VlessPort:         443,
				RealityPubKey:     xrayKeys.PublicKey,
				RealityShortID:    xrayKeys.ShortID,
				RealityServerName: "dl.google.com",

				AwgEnabled:      true,
				AwgPort:         51820,
				AwgServerSubnet: "10.8.0.1/16, fd00:8::1/64",
				AwgPubKey:       awgKeys.PublicKey,
				AwgJc:           awgParams.Jc,
				AwgJmin:         awgParams.Jmin,
				AwgJmax:         awgParams.Jmax,
				AwgS1:           awgParams.S1,
				AwgS2:           awgParams.S2,
				AwgH1:           awgParams.H1,
				AwgH2:           awgParams.H2,
				AwgH3:           awgParams.H3,
				AwgH4:           awgParams.H4,
			}
			if err := db.Create(&demoNode).Error; err == nil {
				log.Printf("[Seed] Demo server node created. One-time node enrollment token: %s", tokenHex)
			}
		}
	}
}
