FROM golang:1.24-alpine AS builder

WORKDIR /app

RUN apk add --no-cache git ca-certificates

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /app/agent ./cmd/agent

FROM alpine:3.20

WORKDIR /app
RUN apk add --no-cache ca-certificates tzdata iptables

COPY --from=builder /app/agent /app/agent

ENTRYPOINT ["/app/agent"]
