name = "freedom-cry-edge"
main = "worker.js"
compatibility_date = "2024-09-01"

# Environment variables
[vars]
ORIGIN_URL = "https://origin.freedomcry.net"
EDGE_SHARED_SECRET = "fc-edge-shield-change-me-in-production"
